# # Send a message to the intent API
# POST http://localhost:3000/api/intent
# Content-Type: application/json

# {
#   "message": "from 20 dai token base to arbitrum"
# }

POST http://localhost:3000/api/routes
Content-Type: application/json

{
  "sourceChain": "base-sepolia",
  "targetChain": "arbitrum-sepolia",
  "token": "MATIC",
  "amount": "0.01"
}
